spring:
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config
      name: gateway
  config:
    import: 'optional:configserver:'

eureka:
  client:
    webclient:
      enabled: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true