apiVersion: v1
kind: Secret
metadata:
  name: graylog-secret
  namespace: default
data:
  # password: admin
  graylogPasswordSecret: #graylogPasswordSecret
  graylogRootPasswordSha2: #graylogRootPasswordSha2