apiVersion: v1
kind: Service
metadata:
  labels:
    app: graylog
  name: graylog
  namespace: default
spec:
  ports:
    - port: 9000 # Graylog web interface and REST API
      protocol: TCP
      targetPort: 9000
      name: web-interface
    - port: 1514 # Syslog TCP
      protocol: TCP
      targetPort: 1514
      name: syslog-tcp
    - port: 1514 # Syslog UDP
      protocol: UDP
      targetPort: 1514
      name: syslog-udp
    - port: 12201 # GELF TCP
      protocol: TCP
      targetPort: 12201
      name: gelf-tcp
    - port: 12201 # GELF UDP
      protocol: UDP
      targetPort: 12201
      name: gelf-upd
  selector:
    app: graylog
  type: ClusterIP