spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      configurations: health-check
    gateway:
      httpclient:
        wiretap: true
      routes:
        - id: game-service
          uri: lb://game-service
          predicates:
            - Path=/game-service/api/**
          filters:
            - StripPrefix=0
        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/file-service/api/**
          filters:
            - StripPrefix=0
        - id: pay-service
          uri: lb://pay-service
          predicates:
            - Path=/pay-service/api/**
          filters:
            - StripPrefix=0

eureka:
  client:
    webclient:
      enabled: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
