spring:
  application:
    name: pay-service
  liquibase:
    liquibase-schema: migration
    default-schema: public
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/gm_payment
    user: postgres
    password: postgres
  r2dbc:
    username: postgres
    password: postgres
    url: r2dbc:postgresql://${DB_HOST:localhost}:5432/gm_payment
  servlet:
    multipart:
      max-file-size: 500KB
      max-request-size: 500KB
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
    topic:
      pay-response: ${PAY_RESPONSE_TOPIC}
      pay-request: ${PAY_REQUEST_TOPIC}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: gamemarket
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'

blockchain:
  node:
    url: ${NODE_URL}
    token: ${NODE_TOKEN}
  contract:
    address: ${CONTRACT_ADDRESS}
    gas-price: 1
    gas-limit: 2000000
    owner-private-key: ${OWNER_PRIVATE_KEY}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}