apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config-datasource
  namespace: default
data:
  datasource.yml: |
    apiVersion: 1

    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        orgId: 1
        url: http://prometheus:9090
        basicAuth: false
        isDefault: true
        editable: true