server:
  port: 8888

spring:
  application:
    name: config
  profiles:
    active: native

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true