apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgresexporter
  name: postgresexporter
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresexporter
  template:
    metadata:
      labels:
        app: postgresexporter
    spec:
      containers:
        - image: prometheuscommunity/postgres-exporter:v0.15.0
          name: postgresexporter
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: DATA_SOURCE_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgresexporter-config
                  key: dataSourceName