apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresexporter
  name: postgresexporter
  namespace: default
spec:
  ports:
    - port: 9187
      protocol: TCP
      targetPort: 9187
  selector:
    app: postgresexporter
  type: ClusterIP