spring:
  liquibase:
    liquibase-schema: migration
    default-schema: public
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/task5
    user: postgres
    password: postgres
  r2dbc:
    username: postgres
    password: postgres
    url: r2dbc:postgresql://${DB_HOST:localhost}:5432/task5
  servlet:
    multipart:
      max-file-size: 500KB
      max-request-size: 500KB
