apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
    tier: database
  name: db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db
        tier: database
    spec:
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pgdata
        - name: init
          configMap:
            name: db-config
      containers:
        - name: db
          image: postgres:12.13-alpine
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          ports:
            - name: db
              containerPort: 5432
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
            - name: init
              mountPath: /docker-entrypoint-initdb.d
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres