apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgdata
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/run/desktop/mnt/host/c/Users/sslot/VirtualValues/gamemarket"